//
//  DebtCalculationEngine.swift
//  SplitIn
//
//  Created by Axel Valent Prayogo on 14/07/26.
//
//  Pure business logic — no SwiftData import, no dependency on the real
//  Bill/BillItem/ItemSplit classes, only on Engine/Protocols. Stateless by
//  design: every call recomputes everything from the raw bills it's given.
//  There is no running-balance state anywhere, so adding/editing/deleting
//  a bill is always self-correcting.
//
//  Split math is weight-based (via `SplitRepresentable.shares`), so equal
//  splits (all shares == 1) and future custom/weighted splits both work
//  through the exact same code path.
//

import Foundation

enum DebtCalculationEngine {

    /// Raw debts generated by a single bill: memberID -> amount owed to the payer.
    /// The payer never appears as a key (you can't owe yourself).
    static func debts(for bill: BillRepresentable) -> [UUID: Decimal] {
        let payerID = bill.paidByID
        var result: [UUID: Decimal] = [:]

        for item in bill.itemsRepresentable {
            let splits = item.splitsRepresentable
            let totalShares = splits.reduce(Decimal(0)) { $0 + $1.shares }
            guard totalShares > 0 else { continue }

            for split in splits where split.memberID != payerID {
                let rawShare = item.totalPrice * (split.shares / totalShares)
                let adjustedShare = rawShare * (1 + bill.adjustmentRate)
                result[split.memberID, default: 0] += adjustedShare
            }
        }
        return result
    }

    /// Nets ALL bills into one pairwise balance per pair of members. Always
    /// recomputed from scratch — pass in every bill in the group, every time.
    /// Positive value at `pair` means `pair.a` owes `pair.b`; negative means
    /// the reverse. Pairs that fully cancel out (== 0) are dropped entirely.
    static func netBalances(bills: [BillRepresentable]) -> [MemberPair: Decimal] {
        var raw: [MemberPair: Decimal] = [:]

        for bill in bills {
            let payerID = bill.paidByID
            for (memberID, amount) in debts(for: bill) {
                let pair = MemberPair(memberID, payerID)
                let sign: Decimal = (memberID == pair.a) ? 1 : -1
                raw[pair, default: 0] += sign * amount
            }
        }
        return raw.filter { $0.value != 0 }
    }

    /// Builds the full "Pay to" / "Collect from" view for every member in
    /// `memberIDs`, from the net pairwise balances.
    static func balanceSheet(bills: [BillRepresentable], memberIDs: [UUID]) -> BalanceSheet {
        let net = netBalances(bills: bills)

        var payTo: [UUID: [BalanceEntry]] = [:]
        var collectFrom: [UUID: [BalanceEntry]] = [:]

        for (pair, amount) in net {
            let (debtorID, creditorID, owed) = amount > 0
                ? (pair.a, pair.b, amount)
                : (pair.b, pair.a, -amount)

            payTo[debtorID, default: []].append(BalanceEntry(counterpartyMemberID: creditorID, amount: owed))
            collectFrom[creditorID, default: []].append(BalanceEntry(counterpartyMemberID: debtorID, amount: owed))
        }

        let balances = memberIDs.reduce(into: [UUID: MemberBalance]()) { result, id in
            result[id] = MemberBalance(
                id: id,
                payTo: payTo[id] ?? [],
                collectFrom: collectFrom[id] ?? []
            )
        }
        return BalanceSheet(balances: balances)
    }
}
